Responsive branch
LuisSalas94/capstone-project-1 pull request #3
Opened 2022-02-01 21:50 UTC by LuisSalas94

**Hello Microvese Team**

On Development, Readme, and Responsive Branch I:
- Added initial linters config
- Added index & about pages
- Added Images file
- Added JavaScript functionality
- Update README.md
- Added link of the live version 
- Added link of Loom video
- Checked responsiveness of the website
- Fixed CSS linters issues
- Fixed JavaScript issues

Cheers and Happy coding!👏👏👏

2022-02-02 00:21 UTC, micheaol requested changes
Hi @LuisSalas94 , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## TO HIGHLIGHT: 

- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

## Suggested changes

- _Please check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-02 00:21 UTC, micheaol commented on css/styles.css
>    .footer.about {
Please ensure that your footer contains a logo aligned to the left and text aligned to the right according to the design. Please also ensure that the footer background color for the Desktop version is dark according to the requirement.

Your Implementation | Project Design
:---:|:---:
![Yours](https://user-images.githubusercontent.com/10332499/152070494-a2e8bc0a-0307-4179-868a-702aa5581f66.PNG) | ![design](https://user-images.githubusercontent.com/10332499/152070531-5810d54b-3448-4c42-b3bf-5030c7c4a51b.PNG)

2022-02-02 00:21 UTC, micheaol commented on css/styles.css
>    .program .row .card {
Please ensure that the pages look almost identical to the original design. And please ensure there are no images or elements blocking the text in both screen sizes.
Your Implementation | Project Design

Your Implementation | Figma Design
:---:|:---:
  
![overlap](https://user-images.githubusercontent.com/10332499/152071480-ac7d5500-59f9-45f3-9709-5174b47b5c48.PNG)  | ![design](https://user-images.githubusercontent.com/10332499/152071501-dfb046de-9d8c-4a71-853f-e81614345b3a.PNG)

2022-02-02 00:21 UTC, micheaol commented on css/styles.css
>    .about-conference {
Please ensure that the pages look almost identical to the original design. And please ensure there are no images or elements blocking the text in both screen sizes.

Your Implementation | Figma Design
:---:|:---:
   
![overlap](https://user-images.githubusercontent.com/10332499/152071756-6a1a8194-e676-4db1-adb2-6c6c4c1f5b06.PNG)  | ![design](https://user-images.githubusercontent.com/10332499/152071786-a0412163-8349-4a63-8c12-d6067c25c9ad.PNG)

2022-02-02 00:21 UTC, micheaol commented on css/styles.css
>    .about-hero {
Please ensure that all images contain `alt` attributes.
https://github.com/LuisSalas94/capstone-project-1/blob/d9f3c12ad21f9b2d87bc33460cee77aab952a0ce/index.html#L38

2022-02-02 20:48 UTC, LuisSalas94 commented on css/styles.css
>    .footer.about {
Hi @micheaol:
I really appreciate your feedback. The footer for the desktop version is not dark but white(#f2f2f2). 
Thank you

2022-02-03 00:20 UTC, Hamzaoutdoors approved these changes
Hey @LuisSalas94, I am **Hamza** your reviewer for this PR 😸 

## Congratulations, Project Approved 🟢 

## To Highlight
✔️ The repo looks professional
✔️ Git/GitHub flow best practices have been followed
✔️ There are no linter errors
✔️ You have a descriptive README
✔️ Wonderful UI design and good choice of theme🥇 
✔️ Great Job building your project with **Mobile-First**


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 14:05 UTC, merged